# Generated by Django 5.1.5 on 2025-04-24 13:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BailApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200)),
                ('case_number', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('bail_application_form', models.FileField(blank=True, null=True, upload_to='bail_documents/application_forms/')),
                ('fir_copy', models.FileField(blank=True, null=True, upload_to='bail_documents/fir_copies/')),
                ('proof_of_address', models.FileField(blank=True, null=True, upload_to='bail_documents/address_proofs/')),
                ('proof_of_identity', models.FileField(blank=True, null=True, upload_to='bail_documents/identity_proofs/')),
                ('affidavit_of_support', models.FileField(blank=True, null=True, upload_to='bail_documents/affidavits/')),
                ('character_reference', models.FileField(blank=True, null=True, upload_to='bail_documents/character_references/')),
                ('criminal_history', models.FileField(blank=True, null=True, upload_to='bail_documents/criminal_history/')),
                ('charges', models.TextField(blank=True)),
                ('bail_amount_requested', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('court_name', models.CharField(blank=True, max_length=200)),
                ('judge_assigned', models.CharField(blank=True, max_length=200)),
                ('hearing_date', models.DateField(blank=True, null=True)),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bail_applications', to='core.incident')),
                ('lawyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bail_applications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
