# Generated by Django 5.1.5 on 2025-04-24 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_judgedecision'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JudgeDecision',
        ),
    ]
